version: 2
updates:
  - package-ecosystem: pip
    directory: /twitter_openapi_python
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: pip
    directory: /twitter_openapi_python_generated
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
